title: Raghavendran Ramakrishnan
description: Machine Learning, Computer Vision
show_downloads: false
google_analytics: UA-155175563-1
theme: jekyll-theme-dinky

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from